/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include  "app.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_1        (GUI_ID_USER + 0x00)
#define ID_BUTTON_BL 			 (GUI_ID_USER + 0x01)

// USER START (Optionally insert additional defines)
extern GUI_CONST_STORAGE GUI_BITMAP bmBLAKE;
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
 { FRAMEWIN_CreateIndirect, " ", ID_FRAMEWIN_1, 0, 0, 800, 480, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_BL, 0, 0, 790, 470, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  // USER START (Optionally insert additional variables)
  // USER END
 int     NCode;
  int     Id;
	
  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Window'
    //
    hItem = pMsg->hWin;
	
			
			hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_BL);
			BUTTON_SetSkinClassic(hItem);
			BUTTON_SetBitmapEx(hItem,0,&bmBLAKE,0,0);
			BUTTON_SetBkColor(hItem,0,GUI_BLACK);
			BUTTON_SetText(hItem, "");
			
	
	
//    WINDOW_SetBkColor(hItem, 0x00000000);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  // USER START (Optionally insert additional message handling)
	
	
	
	 case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    	switch(Id) 
			{
				case ID_BUTTON_BL: //BUTTON_0的通知代码，控制LED1
					hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_BL);
					switch(NCode) 
					{
						case WM_NOTIFICATION_CLICKED:
							break;
						case WM_NOTIFICATION_RELEASED: //按钮被按下并释放
							
						OS_INFO("BlackDLG delete\n");

						tpad_flag=1;
							break;	
					}
			}
	 
	
		break;
	 

//	case WM_DELETE:
//		// 关闭
//		OS_INFO("BlackDLG delete\n");
//		Flag_ICON8 = 0;
//		UserApp_Flag = 0;
//    tpad_flag=1;  
//	

	  break;
	
	
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/

void FUN_ICON8Clicked(void) 
	{
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, HDTWIN, 0, 0);
 
	while(Flag_ICON8)
  {
		
    if(tpad_flag)
			{
				Flag_ICON8=0;
				tpad_flag=0;
				UserApp_Flag = 0;
				WM_DeleteWindow(hWin);  
			}
    GUI_Delay(5);
  }
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
