/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include  "app.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_1        (GUI_ID_USER + 0x00)


// USER START (Optionally insert additional defines)
extern GUI_CONST_STORAGE GUI_BITMAP bmdd2;
extern GUI_CONST_STORAGE GUI_BITMAP bmIOTQ;
extern GUI_CONST_STORAGE GUI_BITMAP bmAPPQ;

extern const unsigned char _acIOTQ[13383UL + 1];

// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "QR", ID_FRAMEWIN_1, 0, 0, 800, 480, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  // USER START (Optionally insert additional variables)
	 WM_HWIN hItem;
//	int     NCode;
//  int     Id;
  // USER END

  switch (pMsg->MsgId) {
  // USER START (Optionally insert additional message handling)
		case WM_INIT_DIALOG://初始化
			
		 // 创建关闭按键
		hItem = pMsg->hWin;
		FRAMEWIN_SetText(hItem,"QR");
		FRAMEWIN_AddCloseButton(hItem,FRAMEWIN_BUTTON_RIGHT,0);
		
		
		
		case WM_DELETE:
		// 关闭
		OS_INFO("QRDLG delete\n");
		Flag_ICON6 = 0;
		UserApp_Flag = 0;
    tpad_flag=0;  

	  break;
		
		
		case WM_PAINT:			
		
		GUI_SetBkColor(GUI_BLACK);
		GUI_Clear();
		//上部渐变线
		GUI_DrawGradientH(400, 0, 800,3,0xF5F200, 0x000000);
		GUI_DrawGradientH(000, 0, 400,3 ,0x000000, 0xF5F200);
		//底部智慧物联系统标题
		GUI_DrawBitmap(&bmdd2,265,404);
		GUI_DrawBitmap(&bmAPPQ,100,100);
		GUI_DrawBitmap(&bmIOTQ,500,100);
		
		break;
		
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/

void FUN_ICON7Clicked(void) {
 
  WM_HWIN hWin;
	OS_INFO("QRDLG create\n");
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, HDTWIN, 0, 0);
	
	while(Flag_ICON7)
  {
    if(tpad_flag)WM_DeleteWindow(hWin);  
    GUI_Delay(5);
  }
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
